services:
  garmin-fetch-data:
    restart: unless-stopped
    build: .
    container_name: garmin-fetch-data
    depends_on:
      - influxdb
    volumes:
      - ./garminconnect-tokens:/home/appuser/.garminconnect 
    env_file:
      - .env.influx
      - .env.garmin
      - .env.user

  influxdb:
    restart: unless-stopped
    container_name: influxdb
    hostname: influxdb
    env_file:
      - .env.influx
    ports:
      - "8181:8181"
    volumes:
      - ./influxdb_data:/data
    image: 'quay.io/influxdb/influxdb3-core:latest'

