services:
  garmin-fetch-data:
    restart: unless-stopped
    build: ./garmin_fetcher
    container_name: garmin-fetch-data
    depends_on:
      - influxdb
    volumes:
      - ./garminconnect-tokens:/home/appuser/.garminconnect 
    env_file:
      - envs/.env.influx
      - envs/.env.garmin
      - envs/.env.user
  
  garmin-enrich-data:
    restart: unless-stopped
    build: ./enricher
    container_name: garmin-enrich-data
    depends_on:
      - influxdb
    env_file:
      - envs/.env.influx
      - envs/.env.user

  influxdb:
    restart: unless-stopped
    container_name: influxdb
    hostname: influxdb
    env_file:
      - envs/.env.influx
    ports:
      - "8181:8181"
    volumes:
      - ./influxdb_data:/data
    image: 'quay.io/influxdb/influxdb3-core:latest'

