services:
  fetcher:
    restart: unless-stopped
    build: ./fetcher
    container_name: fetcher

    depends_on:
      - influxdb
    volumes:
      - ./garminconnect-tokens:/home/appuser/.garminconnect # (persistent tokens storage - garminconnect-tokens folder must be owned by 1000:1000) - should be './garminconnect-tokens:/root/.garminconnect' instead if you are using using user: root
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8181 # Influxdb V3 maps to 8181 instead of 8086 of V1
      - INFLUXDB_USERNAME=influxdb_user # user should have read/write access to INFLUXDB_DATABASE (Required for influxdb 1.x, ignore for influxdb 3.x - set the 3.x specific variables)
      - INFLUXDB_PASSWORD=influxdb_secret_password # (Required for influxdb 1.x, ignore for influxdb 3.x - set the 3.x specific variables)
      - INFLUXDB_DATABASE=GarminStats
      - GARMINCONNECT_IS_CN=False # Set this to True if you are in mainland China or use Garmin-cn (Default False)
      #####################################################################################
      - GARMINCONNECT_EMAIL=${GARMINCONNECT_EMAIL} # optional, read the setup docs. (remove or comment out this line altogether if not used)
      - GARMINCONNECT_BASE64_PASSWORD=${GARMINCONNECT_BASE64_PASSWORD} # optional, must be Base64 encoded, read setup docs. (remove or comment out this line altogether if not used)
      #####################################################################################
      # The following ENV variables are required only if you are using influxdb V3 (You won't have to set the above )
      #####################################################################################
      - INFLUXDB_VERSION=3 # Required for influxdb V3, Default is 1, must be overridden with 3 if using Influxdb V3
      - INFLUXDB_V3_ACCESS_TOKEN=apiv3_bedN6LeAHicTnwsX_hB-k4zUIUh2yKm9ZBTqY86823hryxxUMumTyx_zP3Um73udsdMiIV6jvVbzza6J0551JQ # Required for influxdb V3 (ignored for V1), Set this to your admin access token (or a token that has database R/W access) - You can generate this by following step 3 notes in the README installation
      #####################################################################################
      # The following ENV variables will override some default settings. 
      # Please read the README guide before using them as they may change how the script behaves
      #####################################################################################
      # - LOG_LEVEL=INFO # change to DEBUG to get DEBUG logs
      # - UPDATE_INTERVAL_SECONDS=300 # Default update check interval is set to 5 minutes
      # - FETCH_SELECTION=daily_avg,sleep,steps,heartrate,stress,breathing,hrv,vo2,activity,race_prediction,body_composition # This enables selection of fetch data : Check Discussion #119 to know what additional options are available (add them seperated by , but without a space)
      # - KEEP_FIT_FILES=False # Stores the FIT files (downloads and saves them) when set to True - read docs for more details
      # - ALWAYS_PROCESS_FIT_FILES=False # Enables processing FIT files even if GPS data is not present in it when set to True, default False
      # - USER_TIMEZONE= # Can hardcode user's timezone - must be a valid TZ identifier like Europe/Budapest without quotes, fetches timezone automatically and dynamically on each run if set to empty (default) - Read docs
      # - INFLUXDB_ENDPOINT_IS_HTTP=True # Set this to False if you are using HTTPS for your influxdb connection (over the internet)
      # - FORCE_REPROCESS_ACTIVITIES=True # Enables re-processing of FIT files on iterative updates when set to True (default), setting to False may save processing time but known for skipping activities

  influxdb:
    restart: unless-stopped
    container_name: influxdb
    hostname: influxdb
    environment:
      - INFLUXDB_DB=GarminStats
      - INFLUXDB_USER=influxdb_user
      - INFLUXDB_USER_PASSWORD=influxdb_secret_password
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
      #############################################################
      # The following ENV variables are applicable for InfluxDB V3
      #############################################################
      - INFLUXDB3_MAX_HTTP_REQUEST_SIZE=10485760
      - INFLUXDB3_NODE_IDENTIFIER_PREFIX=Influxdb-node1
      - INFLUXDB3_BUCKET=GarminStats
      - INFLUXDB3_OBJECT_STORE=file
      - INFLUXDB3_DB_DIR=/data
      - INFLUXDB3_QUERY_FILE_LIMIT=5000 # this set to be a very high value if you want to view long term data
    expose:
      - '8181' # Influxdb V3 should expose "8181" (Change INFLUXDB_PORT on garmin-fetch-data appropriately for InfluxDB V3)
    # ports:
    #   - '8181:8181'
    volumes:
      - ./influxdb3-data:/data # InfluxDB V3 bind mount should be set like - influxdb_data:/data if you set INFLUXDB3_DB_DIR=/data (instead of /var/lib/influxdb)
    image: 'quay.io/influxdb/influxdb3-core:latest' # You must change this to 'quay.io/influxdb/influxdb3-core:latest' for influxdb V3

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    hostname: db # This allows other services to connect using the name 'db'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=garmin_app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      # Optional: Expose the port to your host machine for debugging
      - "5432:5432"

volumes:
  postgres_data: