services:
  fetcher:
    restart: unless-stopped
    build: ./fetcher
    container_name: fetcher
    depends_on:
      - influxdb
    volumes:
      - garminconnect_tokens:/home/appuser/.garminconnect
    environment:
      - INFLUXDB_VERSION=3
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8181
      - INFLUXDB_DATABASE=${INFLUXDB3_RAW_BUCKET}
      - INFLUXDB_V3_ACCESS_TOKEN=${INFLUXDB3_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB3_ORG}

      - GARMINCONNECT_IS_CN=False
      - GARMINCONNECT_EMAIL=${GARMINCONNECT_EMAIL}
      - GARMINCONNECT_BASE64_PASSWORD=${GARMINCONNECT_BASE64_PASSWORD}
      - USER_TIMEZONE=Europe/London
      - TOKEN_DIR=/home/appuser/.garminconnect

  enricher:
    restart: unless-stopped
    build: ./enricher
    container_name: data-enricher
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8181
      - INFLUXDB_TOKEN=${INFLUXDB3_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB3_ORG}
      - INFLUXDB_RAW_BUCKET=${INFLUXDB3_RAW_BUCKET}
      - INFLUXDB_ENRICHED_BUCKET=${INFLUXDB3_ENRICHED_BUCKET}

  influxdb:
      # Use the specific version you requested
      image: influxdb:3.3-core
      restart: unless-stopped
      ports:
        # Exposes the container's port 8086 on your machine's port 8181
        - '8181:8181'
      volumes:
        # The native path for InfluxDB v3 data is /var/lib/influxdb3
        - influxdb_data:/var/lib/influxdb3
      environment:
        - INFLUXDB_CONFIG_PATH=/etc/influxdb3/influxdb3.config
        - INFLUXDB_ADMIN_TOKEN=${INFLUXDB3_ADMIN_TOKEN} # Loaded from your .env file
      command:
        - serve
        - --http-bind          # <-- Add this line
        - 0.0.0.0:8181 
        - --object-store
        - file
        - --node-id
        - my-influxdb-node
        - --data-dir
        - /var/lib/influxdb3



volumes:
  influxdb_data:
  garminconnect_tokens: 